services:

  api:
    build: .
    ports:
      - 8082:80
    volumes:
      - ./api:/var/www/html/

  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo

volumes:
  pgadmin-data:
  db-data: